//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-07-14 16:00:57 by NEPU.LiGH
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Anydrill.UBD.Models
{
	/// <summary>
    /// 实体-dsCase 
    /// </summary>
	public class dsCase
    {
		[System.ComponentModel.DataAnnotations.KeyAttribute]
        public Guid ID { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string Name { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string UBDType { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string CirculationType { get; set; }
        public double? StartMD { get; set; }
        public double? EndMD { get; set; }
        public double? Interval { get; set; }
        public double? ROP { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string UseModule { get; set; }
        public double? NPV { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string Operator { get; set; }
        public bool? IsDone { get; set; }
        public DateTime? DoneDate { get; set; }
        public double? SPP { get; set; }
        public double? PAB { get; set; }
        public double? BHP { get; set; }
        public double? SCP { get; set; }
        public double? Temperature { get; set; }
        public double? BackPress { get; set; }
        public double? AtmosphericPressure { get; set; }
        public double? Altitude { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string WellTrajectoryType { get; set; }
        public Guid? WellTrajectoryID { get; set; }
        public Guid? WellStructureID { get; set; }
        public Guid? StratigraphyID { get; set; }
        public Guid? CoiledTubingDesignID { get; set; }
        public Guid? CoiledTubingID { get; set; }
        public Guid? FluidID { get; set; }
        public Guid? BitNozzleID { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(500)]
        public string Remarks { get; set; }
        public Guid? WellID { get; set; }
	}
}



