//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-07-14 16:00:57 by NEPU.LiGH
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Anydrill.UBD.Models
{
	/// <summary>
    /// 实体-dsCoiledTubing 
    /// </summary>
	public class dsCoiledTubing
    {
		[System.ComponentModel.DataAnnotations.KeyAttribute]
        public Guid ID { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string Model { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        public string SteelGrade { get; set; }
        public double? OD { get; set; }
        public double? InD { get; set; }
        public double? Roughness { get; set; }
        public double? WallThickness { get; set; }
        public double? UnitWeight { get; set; }
        public double? MinWallThickness { get; set; }
        public double? HydrostaticPressure { get; set; }
        public double? TubeYieldLoad { get; set; }
        public double? InnerYieldPressure { get; set; }
        public double? YieldTorque { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(500)]
        public string Description { get; set; }
	}
}



