//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-07-14 16:00:57 by NEPU.LiGH
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Anydrill.UBD.Models
{
	/// <summary>
    /// 实体-dsWellTrajectoryPoint 
    /// </summary>
	public class dsWellTrajectoryPoint
    {
		[System.ComponentModel.DataAnnotations.KeyAttribute]
        public Guid ID { get; set; }
        public int? Num { get; set; }
        public double? Depth { get; set; }
        public double? Azimuth { get; set; }
        public double? HoleAngle { get; set; }
        public double? CloseDirection { get; set; }
        public double? CloseDistance { get; set; }
        public double? VertDepth { get; set; }
        public double? NSShift { get; set; }
        public double? WEShift { get; set; }
        public double? DogLeg { get; set; }
        public Guid WellTrajectoryID { get; set; }
	}
}



