//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2017-07-14 16:00:57 by NEPU.LiGH
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Anydrill.UBD.Models
{
	/// <summary>
    /// 实体-dsWellStructureSub 
    /// </summary>
	public class dsWellStructureSub
    {
		[System.ComponentModel.DataAnnotations.KeyAttribute]
        public Guid ID { get; set; }
        public int SpudSequence { get; set; }
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        public string SpudName { get; set; }
        public string SpudDescription { get; set; }
        public double? Depth { get; set; }
        public double? CasingSize { get; set; }
        public double? CasingSettingDepth { get; set; }
        public double? CementTop { get; set; }
        public double? BitSize { get; set; }
        public double? MDTop { get; set; }
        public double? MDBottom { get; set; }
        public double? CasingRoughness { get; set; }
        public double? DiameterEnlargement { get; set; }
        public Guid WellStructureID { get; set; }
	}
}



